### ISSUE TITLE
Simplify {{ .RELEASE }} and {{normalise .RELEASE }} logic

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#110]
If we update the benchmarking plugin to NOT add "v" to the version number than can directly use {{ .RELEASE }} and for `quay.io/prometheus/prometheus:{{ .RELEASE }}` can just add the `v` in manually  as `quay.io/prometheus/prometheus:v{{ .RELEASE }}`

this will remove the need for all `{{ normalise .RELEASE }}` and the normalise function as well.

**Comment by CrazyByDefault** [comment]
Isn't the purpose of the normalise function to replace all `.` with `-` in the version number (from `2.3.0` to `2-3-0`), since k8s config files can't have `.`? We'll still need it even if the benchmarking plugin doesn't add the "v"

**Comment by krasi-georgiev** [comment]
yes you are right, not sure what I was thinking
