### ISSUE TITLE
Think how to simplify the prombench Dockerimage to NOT build a new one on every config file change

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#117]
```
COPY components/prombench/nodepools.yaml /prombench/components/prombench/nodepools.yaml
COPY components/prombench/manifests/benchmark /prombench/components/prombench/manifests/benchmark
```

Currently we copy the configs inside the image itself so any change to these will requires a new image to be build and pushed.

I am thinking if these are either pulled from master from within the prombench image or added as config maps would this simplify the workflow?

**Comment by krasi-georgiev** [comment]
> Create all files present in components/prombench/manifests/benchmark as
config-maps and volume-mount them in prowjobs.
We can use https://github.com/kubernetes/git-sync or https://github.com/WanderaOrg/git2kube to keep the configmap in sync with the git repository.
(@krasi-georgiev might not like adding new dependencies stuck_out_tongue_closed_eyes )

 very good ideas, but new dependancies require more maintenance :) lets leave this as a last resource.



> Implement something like kubectl apply in the prombench-cli tool.
https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#kubectl-apply.
When we pass a http address it will pull it from there.

I am leaning towards this idea with the only drawback that we need to either drop support for parsing entyre folders, which is not a very big deal just more verbose (to specify each file) or implement 
https://github.com/src-d/go-git with 
https://github.community/t5/How-to-use-Git-and-GitHub/How-can-I-download-a-specific-folder-from-a-GitHub-repo/m-p/95#M23

> Implement a new tool which clones the prombench repo in the prowjobs and deploys the yaml files in components/prombench/manifests/benchmark
https://github.community/t5/How-to-use-Git-and-GitHub/How-can-I-download-a-specific-folder-from-a-GitHub-repo/m-p/95#M23
https://github.com/src-d/go-git

don't need a new tool for this can all be done in prombench

> Create a new prow-plugin or modify prometheus/test-infra/prow/plugins/updateconfig plugin.
(This method has a low priority because if we decide not to use prow one day, we want the transition to be as smooth as possible.)

yes will try this of everything else fails.

**Comment by geekodour** [comment]
in my experience, the current docker image is not completely standalone. 
- [/components/prombench/manifests/results/authenticate_rbac.yaml](https://github.com/prometheus/prombench/blob/master/components/prombench/manifests/results/authenticate_rbac.yaml)
- [/components/prow/manifests/rbac.yaml](https://github.com/prometheus/prombench/blob/master/components/prow/manifests/rbac.yaml)

I faced rbac issues when the above two manifests were not applied, I think we can move these to [1b_serviceaccount.yaml](https://github.com/prometheus/prombench/blob/master/components/prombench/manifests/benchmark/1b_serviceaccount.yaml) and [1c_cluster-role-binding.yaml](https://github.com/prometheus/prombench/blob/master/components/prombench/manifests/benchmark/1c_cluster-role-binding.yaml) respectively.

+1 for the idea of pulling from a http address like this:
`kubectl create -f https://raw.githubusercontent.com/user/project/file.yaml`

Will probably just have to add few more lines to the Makefile and add http path support to `/pkg/provider/provider.go:DeploymentsParse` if we do that as @sipian suggested.

**Comment by krasi-georgiev** [comment]
yep lets try that.

**Comment by krasi-georgiev** [comment]
> Create all files present in components/prombench/manifests/benchmark  as
config-maps and volume-mount them in prowjobs .
We can use kubernetes/git-sync or WanderaOrg/git2kube to keep the configmap in sync with the git repository.
(@krasi-georgiev might not like adding new dependencies stuck_out_tongue_closed_eyes )

on a second thought I think this would be the best solution here. The extra dependency is only needed for the automated tests triggered from a comment so it is fine. Don't think it can be avoided as it would be required to monitor config map changes for the other components as well.
