### ISSUE TITLE
When deleting the namepsace do we need to wait until it is confirmed to be deleted?

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#119]
To avoid the long delay why don't we just send the delete request and continue with deleting the nodepools?

I think it will be deleted in the background and even if fails there is nothing we can do in the automation so maybe there is no reason to check the status to make sure it is deleted before continuing

**Comment by sipian** [comment]
sounds good to me

**Comment by geekodour** [comment]
How long does namespace delete take? (`make resource_delete`) it's taking 3-4 secs for me. am I doing something wrong?

when running `make nodepool_delete` , I get the `FailedPrecondition` error but no previous nodepool operation was running. while this does trigger the delete operation in gke for the first node(`prometheus-{{ .PR_NUMBER }}`)
```
04:23:25 provider.go:33: Request for 'deleting nodepool:prometheus-5414' is in progress. Checking in 10s
04:23:36 gke.go:376: Cluster in 'FailedPrecondition' state 'rpc error: code = FailedPrecondition desc = Operation operation-1555022722477-0997d22f is currently deleting a node pool for cluster prombench. Please wait and try again once it is done.'
```

it takes a little more than 30 tries so it exits prombench and it the second nodePool never gets deleted (L339)
https://github.com/prometheus/prombench/blob/cb798a0564e0e3a78f15c9dc8d916e677e62d6a6/pkg/provider/gke/gke.go#L339-L355


running `make nodepool_delete` again deletes both of the nodes. (*3 of them one having 2 replicas)

**Comment by krasi-georgiev** [comment]
lets deal with the high priority issues first and can revisit this one.

The one for the deployment logs is interesting if we can get it closed.
