### ISSUE TITLE
Replace the current  scaler with the prombench cli to scale up and down the  replicas set.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#124]
The current python scaler is broken so instead of trying to fix it lets just use the prombench cli.

/prombench deployment apply -f fake-webserver.yaml -v REPLICAS=300
/prombench deployment apply -f fake-webserver.yaml -v REPLICAS=500

**Comment by sipian** [comment]
I would prefer fixing the loadgen-scaler python code(Appropriate RBAC permissions need to be fixed in the manifest files).
Using prombench CLI tool, we will need to add bash scripts which run infinite loops and sleep(15).

I would like to keep both the loadgen code in 1 place

**Comment by sipian** [comment]
I have the code almost ready with the loadgen-scaler fix

**Comment by krasi-georgiev** [comment]
you can do it without bash just write a small golang tool that imports prombench and run the logic inside.

I am not familiar with python and I think most other maintainers would prefer this in golang as well.
