### ISSUE TITLE
Link to the current PR Grafana dashboard when posting comments 

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#137]
currently I click on the link and than need to remember which was the PR so that I can use the drop-down menu in grafana to select it.

Not a big deal, but if not a big job a click should directly open the dashboard for that PR test.

**Comment by Supposethat4** [comment]
Hi, Grafana Team I've installed plugins and those installed plugins are showing in plugin folder of grafana but when i open dashboard those plugins are not showing in dashboard can you please provide me any solution ?? Anyone of you faced this issue and did you fix it . Just let me know. Thanks
