### ISSUE TITLE
Fix and add test for go vet errors.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#152]
This would be a good test to add as a first with travis.

first suggested in: https://github.com/prometheus/prombench/pull/150

this might be helpful for other tests.
https://github.com/diazjf/fakeclient

**Comment by nikita-mk** [comment]
I wish to work on this. Can someone give me a few pointers?

**Comment by nikita-mk** [comment]
I would like to work on this issue.
