### ISSUE TITLE
Display deployment logs

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#157]
We should look into displaying some logs from some deployments for troubleshooting and debug information.

for example for both tested prometheus servers - we want to see if the stdout/stderr shows any errors during the benchmark.

Currently these are only visible in the GKE console.

**Comment by krasi-georgiev** [comment]
the http://prombench.prometheus.io console displays logs only for the cluster node and deployments creations and not the logs from the deployment itself. I think we should keep it this way and for the pods/deployment  logs should have different window separated by each deployment.
Otherwise showing all in the same window would be too busy and render these unusable.

**Comment by krasi-georgiev** [comment]
bumping to urgent as currently without the logs  there is no way to know what went wrong when a benchmark test shows some problems.

the most important logs would be for both Prometheus deployments.

**Comment by krasi-georgiev** [comment]
maybe the easiest way to solve this is to enable a k8s dashboard with read only access for all deployments.

**Comment by sipian** [comment]
We can create a sidecar which uses stackdriver API to get the logs.

**Comment by krasi-georgiev** [comment]
lets see if we can use some more generic solution not specific to any provider.

**Comment by sipian** [comment]
I am picking this up now.
Looks like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/logs/logs.go is a good place to start with this.

**Comment by krasi-georgiev** [comment]
main question is where would we save and display these? with minimal or no maintenance.

**Comment by sipian** [comment]
As discussed offline, instead of reinventing the wheel, we should wait for logging in grafana.
https://speakerdeck.com/davkal/osmc-2018-logging-is-coming-to-grafana?slide=20

**Comment by CrazyByDefault** [comment]
I believe we can now go ahead with this with using [Loki](https://github.com/grafana/loki) for Grafana, which is their logging system

**Comment by krasi-georgiev** [comment]
yep that is right. feel free to take this one

**Comment by CrazyByDefault** [comment]
Just realized (from https://grafana.com/loki) - 

> Loki is currently in alpha. You **should not** depend on it for production use.

Would it be wise to implement this before Loki is close to finished? Or should we look for aternatives or put this on hold till Loki becomes more stable?

**Comment by krasi-georgiev** [comment]
I think it is fine to use even when in alpha as it would be better than no logs at all(which is what we have now).
