### ISSUE TITLE
add /benchmark restart

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#162]
After running some benchmark I realised that my PR needed rebasing so I had rebase ,  cancel , wait for it to be cancelled and start it again.

If we have /benchmark restart than it would save me waiting for the last one to be cancelled so I can start a a new one.

**Comment by nikita-mk** [comment]
I will work on this.

**Comment by geekodour** [comment]
@nikita-mk I am working on a PR to make the benchmark plugin an external plugin to prow after that adding this feature should be easier.
