### ISSUE TITLE
Some t2.mediums are created which end up dead pretty soon

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prombench#17]
Because of how we update the default nodes IG, 1-3 nodes are usually `t2.medium` instances which end up as Unready within an hour as they exhaust their CPU credit. 

We should do a rolling update instead of just an edit [here](https://github.com/prometheus/prombench/blob/master/Makefile#L42)

Ref: https://github.com/kubernetes/kops/issues/2650

**Comment by brancz** [comment]
we can use the `--node-size` flag on the kops create cluster command, that way we can avoid ever starting t2.mediums
