### ISSUE TITLE
use prombench to deploy the prow cluster.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#26]
at the moment we depend on terraform to deploy the prow cluster. this can be achieved using the prombench tool itself so no need to have any other dependencies.

**Comment by krasi-georgiev** [comment]
We are still using kubectl for some parts. Lets close once we use prombench for everything.

**Comment by geekodour** [comment]
@krasi-georgiev this can be closed now.

**Comment by krasi-georgiev** [comment]
Thanks,

don't forget to put  `fixes: #ISSUES_NUMBER` in pr's that close an issue.
