### ISSUE TITLE
auto build prombench apps from source or push to a central repo on every change.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#28]
at the moment the fake webserver and the python loader are manually build and pushed to a central repo.

It would be better if prow builds these from source or if we use circle to build and auto push these to quay or docker hub.

**Comment by sipian** [comment]
fake-webserver and python-loadgen are fairly stabilized and need very minimal changes. 
I don't see much reason to automate them.

**Comment by krasi-georgiev** [comment]
you are right it these start to need frequent changes will revisit.

after the duscussion today it seems that we would have
 - prombench docker image - to create/delete clusters/nodes pod deployments.
 - prometheus runner - which will build and run a prometheus from a mounted src folder.
 - fake-webserver
 - python-loadgen
