### ISSUE TITLE
Post a GitHub comment or cancel test if the maintainer forgets to comment /benchmark cancel

### ISSUE THREAD

**Issue by sipian** [prometheus/prombench#31]

**Comment by sipian** [comment]
Should prow just send reminders or trigger `/benchmark cancel`itself?
Maybe we can do something like
- Post a comment in the PR every 12hours(or 4 hours?) that benchmarking is going on
- Do this at max 3 times. If deployment is still active, trigger `/benchmark cancel`

**Comment by krasi-georgiev** [comment]
yeah that sound reasonable. one comment every 12h for 3 days and cancel after that.

**Comment by geekodour** [comment]
I am working on a implementation of an external benchmark plugin for prow (which will eventually be the hook endpoint for github actions), I'll try to add parts of #174 into the new external benchmark plugin.

prow plugins already have access to github client and info about the running jobs so it will be easier to implement (we can add a flag to enable disable the reminder or customize intervals) also this will avoid adding another component (reminder) to prombench itself. I'll try to send the PR soon.

**Comment by krasi-georgiev** [comment]
closed in https://github.com/prometheus/prombench/pull/234
