### ISSUE TITLE
Add authentication & https to the Prometheus & grafana links being exposed.

### ISSUE THREAD

**Issue by sipian** [prometheus/prombench#33]
Currently, anyone can view the Grafana & Prometheus-Meta dashboard being deployed.
The different ways of allowing authentication can be:
1. Use [OAuth2 Proxy](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth) to add authentication via GitHub to the exposed ingress IP. Access can be restricted to just the organization members.  
2. Allow prometheus-meta to be accessible by anyone, but expose Grafana [snapshots](http://docs.grafana.org/reference/sharing/) to everyone. 
Kubernetes team uses this approach for [velodrome](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1).

Also will be cool if we could add TLS on all these exposed ingress paths.

**Comment by sipian** [comment]
AFAIK exposing Grafana snapshots will involve deploying 1 Grafana server(instead of deploying a new server for every benchmarking event).

New datasources, dashboards & snapshots can be made by using a Kubernetes Job that executes curl commands to deploy Grafana components using Grafana's http API.
A sample k8s job can be found [here](https://github.com/kayrus/prometheus-kubernetes/blob/master/grafana-deployment.yaml#L50)

**Comment by brian-brazil** [comment]
> Currently, anyone can view the Grafana & Prometheus-Meta dashboard being deployed.

Why is that  a problem?

**Comment by sipian** [comment]
In the current setup, to view the grafana graphs, the user needs to login first.
I am more inclined to use option 2 so that grafana graphs can be viewed without requiring any login.

**Comment by brian-brazil** [comment]
Grafana can be setup to allow anonymous access. 

We're an open source project, there's nothing to hide about our benchmark graphs.

**Comment by krasi-georgiev** [comment]
lets close and revisit if needed.

**Comment by sipian** [comment]
Authentication part of this issue has been handled by allowing anonymous access to grafana graphs
