### ISSUE TITLE
Implement a better logger - go kit log

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#35]
at the moment we are using the "log" package , but this is missing some nice features like showing the file name and line position where the log came from.

**Comment by dimitrovvlado** [comment]
@krasi-georgiev 
I know it doesn't exactly follow the description of the issue (introducing a new dep), but it is possible to display the source file and line number with the standard logger as proposed here: https://github.com/prometheus/prombench/pull/153

**Comment by krasi-georgiev** [comment]
closed in https://github.com/prometheus/prombench/pull/153
