### ISSUE TITLE
Remove design.md and add the information to the main README.md

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#39]

**Comment by sipian** [comment]
The schema diagram in the readme pretty much sums up design.md. 
Do we really need to add design.md information to readme.md?
The information that I think can be worth mentioning is the link to the [proposal](https://docs.google.com/document/d/1aCGHS0hOrh3LiQLuOa1EWA6knF7HmqWbhp3ev66hB7Y/edit?ouid=118160464041419930165&usp=docs_home&ths=true)

**Comment by krasi-georgiev** [comment]
I want to add something like a - The life of a prombench job.
It  will describe step by step what happens from /bench .... trough GKE nodepool create , prometheus-meta , grafana , alertmanager , alertmanager-github-bridge etc....
