### ISSUE TITLE
When applying some resource files getting an error:  Invalid value: "": must be specified for an update

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#44]
prombench gke resource apply -a $AUTH_FILE -v ZONE:$ZONE -v CLUSTER_NAME:$CLUSTER_NAME \
-v GCLOUD_SERVICEACCOUNT_CLIENTID:$GCLOUD_SERVICEACCOUNT_CLIENTID \
-f components/prow/manifests/rbac.yaml -f components/prow/manifests/nginx-controller.yaml

for example applying this twice renders the error below

error while applying a resource err:apply resources from manifest file:components/prow/manifests/nginx-controller.yaml: resource update failed - kind: Service, name: default-http-backend: Service "default-http-backend" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]

**Comment by sipian** [comment]
If a resource is already present in the cluster, gke tool will update it.
Acc to [this](https://www.timcosta.io/kubernetes-service-invalid-clusterip-or-resourceversion/), if we try to update a service, we will get this error.
If a user needs to update his service, he needs to add some annotations in his service-config.yaml file

**Comment by krasi-georgiev** [comment]
maybe we should try applying the fix at the end of the page in gke.

**Comment by sipian** [comment]
This will involve changing the service config in the manifest files.
No change needs to be done in gke tool

**Comment by krasi-georgiev** [comment]
the article mentiones that if you first run
`kubectl annotate svc my-service kubectl.kubernetes.io/last-applied-configuration-`
than the update will succeed 
so I was thinking to send this api request from the gke before updating a service.

**Comment by krasi-georgiev** [comment]
I just tried it, but doesn't remove the error.

**Comment by sipian** [comment]
Adding this annotation field should be left to the choice of the user.
Some users might want to keep this check(maybe to prevent load balancer IP address being changed accidentally)
