### ISSUE TITLE
Add info  how to upgrade/update  prow and benchmarking configs and upgrades.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#60]
- [ ] how to upgrade a prow component
- [ ] how to change prow job settings
- [ ] how to upgrade a bench component.
- [ ] how to change settings for different components.

**Comment by geekodour** [comment]
The [config-updater plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/updateconfig) in prow is really great for this purpose. I think we can use the hook component of prow even after we migrate to github actions. I've tested it and will add it the PR to upgrade prow. 

can also be useful when we update grafana dashboard files. 

When a config file(s) configured in the `config-updater` is merged it automatically updates that config map in kubernetes and posts a comment in the merged PR.

But I think if we use this we should not add the configmap of `prometheus.yml ` for the `test-prometheus` instances as some merge can happen in the middle of a running benchmark and it can affect the results somehow. or not? (related https://github.com/prometheus/prombench/issues/117 )

**Comment by krasi-georgiev** [comment]
yep sound like a good plan, thanks for looking into this.

Lets leave it for after closing the High priority issues first.

**Comment by geekodour** [comment]
Think we can close this too?
