### ISSUE TITLE
Add kube-state-metrics deployment and grafana graphs

### ISSUE THREAD

**Issue by sipian** [prometheus/prombench#76]
It will be good to have grafana dashboards that display cluster status, so that users can view what amount of load is being put onto the prometheus servers.
I have tried a few grafana dashboards like [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus), etc but I wasn't fully satisfied with the graphs.

[grafana-kubernetes-app](https://github.com/grafana/kubernetes-app) looks like a good option. Instead of using grafana-plugin, can convert the [grafana-kubernetes-app-dashboards](https://github.com/grafana/kubernetes-app/tree/master/src/dashboards) for prombench.

**Comment by geekodour** [comment]
@simonpasquier @krasi-georgiev can `kube-state-metrics` provide a better metric to detect how long tests have been running instead of using `node_boot_time_seconds`?

ref to @simonpasquier 's comment: https://github.com/prometheus/prombench/pull/208#discussion_r302716682

**Comment by simonpasquier** [comment]
yes `kube_namespace_created` could probably be used.

**Comment by simonpasquier** [comment]
yes [`kube_namespace_created`](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/namespace-metrics.md) could probably be used.
