### ISSUE TITLE
Use a service name instead of ingress ip for grafana.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#77]
It would be less prone to error if we use the prometheus-meta service name instead of the ingress ip

We still want to expose prometheus-meta, but for any connection between the internal components would be best to use service names instead of external IP addresses.

**Comment by geekodour** [comment]
@krasi-georgiev with ref to you comment on #188 related to using the k8s api to set the `INGRESS_IP`, do you think by replacing the `INGRESS_IP` with `prombench.prometheus.io` in the manifest files would be a good idea? then we don't even need to use the `INGRESS_IP`.

also, I think making `prombench.prometheus.io` be set using a DeploymentVariable will be even better because we'll be able to test prombench in a staging/testing environment with some other custom domain then.



```
λ  prombench (networkingIngress) × grep -rn INGRESS_IP --exclude=README.md
components/prombench/manifests/results/prometheus-meta.yaml:22:    # web.external-url of INGRESS_IP/prometheus-meta/
components/prombench/manifests/results/prometheus-meta.yaml:135:        - "--web.external-url=http://{{ .INGRESS_IP }}/prometheus-meta"
components/prombench/manifests/results/grafana_deployment.yaml:29:            value: "http://{{ .INGRESS_IP }}/grafana"
components/prombench/manifests/results/grafana_datasource.yaml:19:      url: http://{{ .INGRESS_IP }}/prometheus-meta/
```
```
λ  prombench (networkingIngress) × grep -rn prombench.prometheus.io --exclude=README.md
cmd/load-generator/main.py:46:            self.url = "http://prombench.prometheus.io/%s/prometheus-%s/api/v1/query" % (pr_number, target)
cmd/load-generator/main.py:48:            self.url = "http://prombench.prometheus.io/%s/prometheus-%s/api/v1/query_range" % (pr_number, target)
components/prow/manifests/prow_internals_2.yaml:191:      job_url_template: 'http://prombench.prometheus.io/log?job={{"{{"}}.Spec.Job{{"}}"}}&id={{"{{"}}.Status.BuildID{{"}}"}}'
components/prombench/manifests/benchmark/3_prometheus-test.yaml:763:          "--web.external-url=http://prombench.prometheus.io/{{ .PR_NUMBER }}/prometheus-pr",
components/prombench/manifests/benchmark/3_prometheus-test.yaml:852:          "--web.external-url=http://prombench.prometheus.io/{{ .PR_NUMBER }}/prometheus-release",

```

let me know what you think.

**Comment by krasi-georgiev** [comment]
I can't even remember what I meant by this issue, but yeah your idea sounds good, just not sure if domain name can be used instead of an IP.

**Comment by krasi-georgiev** [comment]
In general hard coding strings like domain names , ip etc is always a bad idea and prone to break so if we can avoid it please go ahead.

**Comment by krasi-georgiev** [comment]
closed in https://github.com/prometheus/prombench/pull/191
